# .github/workflows/upload-source-package.yml
name: Upload Source Package to OSS

on:
  workflow_call:

env:
  OSS_ACCESS_KEY_ID: ${{ secrets.ALIBABA_CLOUD_ACCESS_KEY_ID }}
  OSS_ACCESS_KEY_SECRET: ${{ secrets.ALIBABA_CLOUD_ACCESS_KEY_SECRET }}
  OSS_BUCKET: ${{ vars.OSS_BUCKET }}
  OSS_REGION: ${{ vars.OSS_REGION }}

jobs:
  upload_source_package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Create source package
        run: |
          echo "Creating source package..."
          zip -r code.zip . -x "*.git*" "*.terraform*"
          if [ ! -f code.zip ]; then
            echo "Error: Failed to create code.zip"
            exit 1
          fi
          echo "Created code.zip with size:"
          ls -lh code.zip

      - name: Setup Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install alibabacloud-oss-v2

      - name: Upload source package
        id: upload_source_package
        run: |
          commit_id=${{ github.event.pull_request.head.sha }}
          object_path="repositories/${{ github.event.repository.full_name }}/${{ github.base_ref }}/code.zip"

          echo "Uploading to OSS with key: $object_path"
          output=$(python scripts/upload_to_oss.py --key="$object_path" --file_path=code.zip --unique_key="$commit_id" 2>&1)

          if [ $? -ne 0 ]; then
            echo "Error: Failed to upload to OSS"
            echo "$output"
            exit 1
          fi

          echo "Upload output: $output"
